using System;
using System.Linq;
using System.Reflection;
using Mono.Cecil;
using Mono.Cecil.Cil;

namespace NameOf.Fody {
    partial class ModuleWeaver {
        private static PatternInstruction[][] nameOfCallPatterns = {
            // The regions below correspond roughly to the patterns generated by their usage. It is not meant to be definitive as there is some overlap.
            #region Instance
		    new [] {
                new PatternInstruction(LoadOpCodes),
                new PatternInstruction(OpCodes.Ldfld),
                new PatternInstruction(OpCodes.Ldfld, (i, p) => ((FieldReference)i.Operand).Name),
                new OptionalPatternInstruction(OpCodes.Box),
                new NameOfPatternInstruction(),
            },
		    new [] {
                new PatternInstruction(LoadOpCodes),
                new PatternInstruction(OpCodes.Ldfld),
                new PatternInstruction(CallOpCodes, (i, p) => ((MethodDefinition)i.Operand).Name.Substring(4), (i, p) => ((MethodDefinition)i.Operand).IsGetter),
                new OptionalPatternInstruction(OpCodes.Box),
                new NameOfPatternInstruction(),
            },
		    new [] {
                new PatternInstruction(LoadOpCodes),
                new PatternInstruction(OpCodes.Ldfld),
                new PatternInstruction(OpCodes.Ldftn, (i, p) => ((MethodReference)i.Operand).Name),
                new OptionalPatternInstruction(OpCodes.Newobj),
                new NameOfPatternInstruction(),
            },
		    new [] {
                new PatternInstruction(LoadOpCodes),
                new PatternInstruction(OpCodes.Ldftn, GetNameFromAnonymousMethod),
                new OptionalPatternInstruction(OpCodes.Newobj),
                new NameOfPatternInstruction(),
            },
		    new [] {
                new PatternInstruction(LoadOpCodes),
                new PatternInstruction(OpCodes.Ldfld),
                new OptionalPatternInstruction(OpCodes.Ldnull),
                //new OptionalPatternInstructionSequences(new [] {OpCodes.Ldnull}, new [] {OpCodes.Ldc_I4_0}, new [] {OpCodes.Ldc_I4_0, OpCodes.Conv_I8}),
                new PatternInstruction(CallOpCodes, (i, p) => ((MethodDefinition)i.Operand).Name, (i, p) => !((MethodDefinition)i.Operand).IsGetter),
                new OptionalPatternInstruction(OpCodes.Box),
                new NameOfPatternInstruction(),
            },
            #endregion
            #region Enum Value
		    new [] {
                new PatternInstruction(new []{OpCodes.Ldc_I4, OpCodes.Ldc_I4_S, OpCodes.Ldc_I8}),
                new PatternInstruction(OpCodes.Box, (i, p) => ((TypeDefinition)i.Operand).Fields.Single(x => (x.Constant ?? String.Empty).ToString() == i.Previous.Operand.ToString()).Name, (i, p) => ((TypeDefinition)i.Operand).IsEnum),
                new NameOfPatternInstruction(),
            },
		    new [] {
                new PatternInstruction(new []{OpCodes.Ldc_I4_M1, OpCodes.Ldc_I4_0, OpCodes.Ldc_I4_1, OpCodes.Ldc_I4_2, OpCodes.Ldc_I4_3, OpCodes.Ldc_I4_4, OpCodes.Ldc_I4_5, OpCodes.Ldc_I4_6, OpCodes.Ldc_I4_7, OpCodes.Ldc_I4_8}),
                new PatternInstruction(OpCodes.Box, (i, p) => ((TypeDefinition)i.Operand).Fields.Single(x => (Int32?)x.Constant == GetNumberAtEndOf(i.Previous.OpCode)).Name, (i, p) => ((TypeDefinition)i.Operand).IsEnum),
                new NameOfPatternInstruction(),
            },
            #endregion
            #region Type
		    new [] {
                new PatternInstruction(OpCodes.Ldtoken, (i, p) => ((TypeDefinition)i.Operand).Name),
                new PatternInstruction(OpCodes.Call, null, (i, p) => ((MethodReference)i.Operand).FullName.StartsWith(GetTypeFromHandleMethodSignature)),
                new NameOfPatternInstruction(),
            },
		    new PatternInstruction[] {
                new NameOfPatternInstruction((i, p) => ((GenericInstanceMethod)i.Operand).GenericArguments[0].Name, (i, p) => i.Operand is GenericInstanceMethod),
            },
            #endregion
            #region Local
		    new [] {
                new PatternInstruction(OpCodes.Ldloc_0, (i, p) => p.Body.Variables[0].Name),
                new OptionalPatternInstruction(OpCodes.Box),
                new NameOfPatternInstruction(),
            },
		    new [] {
                new PatternInstruction(OpCodes.Ldloc_1, (i, p) => p.Body.Variables[1].Name),
                new OptionalPatternInstruction(OpCodes.Box),
                new NameOfPatternInstruction(),
            },
		    new [] {
                new PatternInstruction(OpCodes.Ldloc_2, (i, p) => p.Body.Variables[2].Name),
                new OptionalPatternInstruction(OpCodes.Box),
                new NameOfPatternInstruction(),
            },
		    new [] {
                new PatternInstruction(OpCodes.Ldloc_3, (i, p) => p.Body.Variables[3].Name),
                new OptionalPatternInstruction(OpCodes.Box),
                new NameOfPatternInstruction(),
            },
		    new [] {
                new PatternInstruction(new[] {OpCodes.Ldloc, OpCodes.Ldloc_S}, (i, p) => ((VariableReference)i.Operand).Name),
                new OptionalPatternInstruction(OpCodes.Box),
                new NameOfPatternInstruction(),
            },
            #endregion
            #region Member
		    new [] {
                new PatternInstruction(OpCodes.Ldsfld, instruction => PotentiallyUnusedFieldDefinitions.Add(instruction.Operand as FieldDefinition)),
                new PatternInstruction(OpCodes.Brtrue_S),
                new PatternInstruction(OpCodes.Ldnull),
                new PatternInstruction(OpCodes.Ldftn, GetNameFromAnonymousMethod),
                new PatternInstruction(OpCodes.Newobj),
                new PatternInstruction(OpCodes.Stsfld),
                new OptionalPatternInstruction(OpCodes.Br_S),
                new PatternInstruction(OpCodes.Ldsfld),
                new NameOfPatternInstruction(),
            },
		    new [] {
                new PatternInstruction(OpCodes.Ldnull), 
                new PatternInstruction(OpCodes.Ldftn, (i, p) => ((MethodReference)i.Operand).Name),
                new PatternInstruction(OpCodes.Newobj),
                new NameOfPatternInstruction(),
            },
		    new [] {
                new PatternInstruction(OpCodes.Ldsfld, (i, p) => ((FieldReference)i.Operand).Name),
                new OptionalPatternInstruction(OpCodes.Box),
                new NameOfPatternInstruction(),
            },
		    new [] {
                new PatternInstruction(OpCodes.Call, (i, p) => ((MethodDefinition)i.Operand).Name.Substring(4), (i, p) => ((MethodDefinition)i.Operand).IsGetter),
                new OptionalPatternInstruction(OpCodes.Box),
                new NameOfPatternInstruction(),
            },
            #endregion
            #region Arguments
		    new [] {
                new PatternInstruction(OpCodes.Ldarg_0, (i, p) => p.Body.Method.Parameters[0].Name),
                new OptionalPatternInstruction(OpCodes.Box),
                new NameOfPatternInstruction(),
            },
            new [] {
                new PatternInstruction(OpCodes.Ldarg_1, (i, p) => p.Body.Method.Parameters[1].Name),
                new OptionalPatternInstruction(OpCodes.Box),
                new NameOfPatternInstruction(),
            },
            new [] {
                new PatternInstruction(OpCodes.Ldarg_2, (i, p) => p.Body.Method.Parameters[2].Name),
                new OptionalPatternInstruction(OpCodes.Box),
                new NameOfPatternInstruction(),
            },
            new [] {
                new PatternInstruction(OpCodes.Ldarg_3, (i, p) => p.Body.Method.Parameters[3].Name),
                new OptionalPatternInstruction(OpCodes.Box),
                new NameOfPatternInstruction(),
            },
            new [] {
                new PatternInstruction(new [] {OpCodes.Ldarg, OpCodes.Ldarg_S}, (i, p) => ((ParameterReference)i.Operand).Name),
                new OptionalPatternInstruction(OpCodes.Box),
                new NameOfPatternInstruction(),
            }, 
            #endregion
        };
        private static PatternInstruction[][] lambdaPatterns = {
            new [] { // Events
                new PatternInstruction(OpCodes.Ldarg_0),
                new OptionalPatternInstruction(OpCodes.Ldfld),
                new OptionalPatternInstruction(OpCodes.Ldarg_1),
                new PatternInstruction(CallOpCodes, (i, p) => ((MethodDefinition)i.Operand).Name.Substring(((MethodDefinition)i.Operand).IsAddOn ? 4 : 7), (i, p) => ((MethodDefinition)i.Operand).IsAddOn || ((MethodDefinition)i.Operand).IsRemoveOn),
                new OptionalPatternInstruction(OpCodes.Nop), // This gets emitted into debug builds
                new PatternInstruction(OpCodes.Ret),
            },
            new [] { // Fields
                new PatternInstruction(OpCodes.Ldarg_0),
                new PatternInstruction(OpCodes.Ldfld, (i, p) => ((FieldReference)i.Operand).Name),
                new OptionalPatternInstruction(OpCodes.Box),
                new OptionalPatternInstruction(OpCodes.Stloc_0),
                new OptionalPatternInstruction(OpCodes.Br_S),
                new OptionalPatternInstruction(OpCodes.Ldloc_0),
                new PatternInstruction(OpCodes.Ret),
            }, 
            new [] { // Properties (getters)
                new PatternInstruction(OpCodes.Ldarg_0),
                new PatternInstruction(CallOpCodes, (i, p) => ((MethodDefinition)i.Operand).Name.Substring(4), (i, p) => ((MethodDefinition)i.Operand).IsGetter),
                new OptionalPatternInstruction(OpCodes.Box),
                new OptionalPatternInstruction(OpCodes.Stloc_0),
                new OptionalPatternInstruction(OpCodes.Br_S),
                new OptionalPatternInstruction(OpCodes.Ldloc_0),
                new PatternInstruction(OpCodes.Ret),
            }, 
            new [] { // Methods
                new PatternInstruction(OpCodes.Ldarg_0),
                new PatternInstruction(OpCodes.Ldftn, (i, p) => ((MethodReference)i.Operand).Name),
                new PatternInstruction(OpCodes.Newobj),
                new OptionalPatternInstruction(OpCodes.Stloc_0),
                new OptionalPatternInstruction(OpCodes.Br_S),
                new OptionalPatternInstruction(OpCodes.Ldloc_0),
                new PatternInstruction(OpCodes.Ret),
            }, 
            new [] { // Method calls
                new PatternInstruction(OpCodes.Ldarg_0),
                new OptionalPatternInstruction(OpCodes.Ldnull),
                new PatternInstruction(CallOpCodes, (i, p) => ((MethodReference)i.Operand).Name, (i, p) => !((MethodDefinition)i.Operand).IsGetter && !((MethodDefinition)i.Operand).IsAddOn && !((MethodDefinition)i.Operand).IsRemoveOn),
                new OptionalPatternInstruction(OpCodes.Stloc_0),
                new OptionalPatternInstruction(OpCodes.Br_S),
                new OptionalPatternInstruction(OpCodes.Ldloc_0),
                new PatternInstruction(OpCodes.Ret),
            }, 
        };

		//private static PatternInstruction[][] defaultKeywordPatterns = {
		//	new [] {
		//		new PatternInstruction(OpCodes.Ldnull),
		//	},
		//	new [] {
		//		new PatternInstruction(OpCodes.Ldc_I4_0),
		//	},
		//	new [] {
		//		new PatternInstruction(OpCodes.Ldloca_S),
		//		new PatternInstruction(OpCodes.Initobj),
		//		new PatternInstruction(new [] {OpCodes.Ldloc_0, OpCodes.Ldloc_1, OpCodes.Ldloc_2, OpCodes.Ldloc_3, OpCodes.Ldloc_S}),
		//	},
		//	new [] {
		//		new PatternInstruction(OpCodes.Ldc_I4_0),
		//		new PatternInstruction(OpCodes.Newobj, null, (i, p) => ((MethodReference)i.Operand) != null/* == typeof(Decimal).GetConstructor(new [] {typeof(Int32)})*/),
		//	},
		//	new [] {
		//		new PatternInstruction(OpCodes.Ldc_R8, null, (i, p) => i.Operand == 0),
		//	},
		//	new [] {
			    
		//	},
		//};
    }
}